from typing import Protocol
class CRM(Protocol):
 async def customer(self,id:str)->dict:...
 async def update_case(self,id:str,patch:dict)->dict:...
class Orders(Protocol):
 async def list_orders(self,customer_id:str)->list[dict]:...
 async def order(self,id:str)->dict:...
class Knowledge(Protocol):
 async def search(self,query:str,tenant_id:str,k:int=5)->list[dict]:...
class Messaging(Protocol):
 async def send(self,channel:str,target:str,body:str)->dict:...
